name: myapp
description: A exported flutter project from FUNCTION12

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/page-1/images/auto-group-fvkx.png
    - assets/page-1/images/dumbbell-solid-1.png
    - assets/page-1/images/rectangle-3.png
    - assets/page-1/images/auto-group-a1xw.png
    - assets/page-1/images/wgjm-unscreen-1-2.png
    - assets/page-1/images/wgjm-unscreen-1-3.png
    - assets/page-1/images/bowl-food-solid-1.png
    - assets/page-1/images/kl-1.png
    - assets/page-1/images/31KL.gif
    - assets/page-1/images/WgjM-unscreen.gif
    - assets/page-1/images/WgjM-unscreen1.gif
    - assets/page-1/images/WgjM-unscreen2.gif
    - assets/page-1/images/auto-group-fvkx.png

